title: Kenna Lewis
email: mckennalewis2019gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kenna Lewis' Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: 
sass:
  load_paths:
    - _sass
plugins:
  - jekyll-feed
include:
  - assets
  - projects

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_nr: 1
  show_warnings: false
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
